title: IL POLIMATE
description: Intelligence Strategica.
author: marcorzzn
email: you@example.com

# URL CONFIGURATION
# Se la tua repo si chiama "The-Polymath-Brief", baseurl DEVE essere "/The-Polymath-Brief"
# Se l'hai rinominata "marcorzzn.github.io", lascialo vuoto ""
baseurl: "/The-Polymath-Brief" 
url: "https://marcorzzn.github.io"

# BUILD SETTINGS
markdown: kramdown
# theme: jekyll-theme-minimal  <-- LO COMMENTIAMO PERCHE' USIAMO IL NOSTRO LAYOUT CUSTOM
permalink: /:year/:month/:day/:title.html
future: true
plugins:
  - jekyll-feed
